import { icon } from "@/assets";
import { Carousel } from "@/components/carousel";
import Head from "next/head";
import { Main } from "./styles";
import * as Style from "./styles";
import { ModelsSection } from "@/components/modelsSection";
import { Fade } from "react-awesome-reveal";
import { FindPorscheSection } from "@/components/findPorsche";

export default function Home() {
  const carouselImages = [
    {
      src: icon.cover1,
      alt: "",
    },
    {
      src: icon.cover2,
      alt: "",
    },
    {
      src: icon.cover3,
      alt: "",
    },
    {
      src: icon.cover4,
      alt: "",
    },
  ];

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Fade>
          <Carousel images={carouselImages} />
        </Fade>

        <Fade fraction={0.1}>
          <ModelsSection />
        </Fade>

        <Fade>
          <FindPorscheSection />
        </Fade>
      </Main>
    </>
  );
}
